# Generated by Django 5.0.3 on 2024-04-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_code',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
