# Generated by Django 5.0.3 on 2024-04-23 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_app', '0004_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='ref_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_by_user', to='ref_app.user'),
        ),
    ]
