# Generated by Django 5.0.3 on 2024-04-23 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ref_app', '0006_remove_user_referred_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='referred_by',
        ),
    ]
