# Generated by Django 5.0.3 on 2024-04-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_app', '0007_remove_user_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='phone_number',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
    ]
