# Generated by Django 5.0.3 on 2024-04-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_app', '0011_alter_referral_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(max_length=20),
        ),
    ]
