# Generated by Django 5.0.3 on 2024-04-23 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ref_app', '0012_alter_referral_referral_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='referral',
            old_name='referral_code',
            new_name='refcode',
        ),
    ]
